name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.tatsatpatel1210@gmail.com }}
        password: ${{ secrets.DockerHub1214 }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.tatsatpatel1210@gmail.com }}/node-hello:latest .
        docker push ${{ secrets.tatsatpatel1210@gmail.com }}/node-hello:latest