apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "node-hello.TatsatPatel" . }}
  labels:
    app: {{ include "node-hello.Tatsat" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "node-hello.Tatsat" . }}
  template:
    metadata:
      labels:
        app: {{ include "node-hello.Tatsat" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000