apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-hello.fullname" . }}
  labels:
    app: {{ include "node-hello.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 3000
  selector:
    app: {{ include "node-hello.name" . }}