image:
  repository: tatsatpatel1210@gmail.com/node-hello
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 3000
  nodePort: 30000

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

# service:
#   type: NodePort
#   port: 3000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}